spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thoughts?serverTimezone=UTC
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true